Repository GTNewHorizons/Railcraft, pull requests merged in 2025-04, with the labels that each got.

#79 Fix railcraft help command
  src/main/java/mods/railcraft/common/commands/CommandHelpers.java
  src/main/java/mods/railcraft/common/commands/IModCommand.java
  src/main/java/mods/railcraft/common/commands/RootCommand.java
  src/main/java/mods/railcraft/common/commands/SubCommand.java
Labels: :construction: Testing on Zeta

#73 add Engineer'Overall API/Move engineer's overall into GregTech hazard system if gregtech is installed
  dependencies.gradle
  gradle.properties
  src/main/java/mods/railcraft/api/core/items/ISafetyPants.java
  src/main/java/mods/railcraft/common/blocks/tracks/BlockTrack.java
  src/main/java/mods/railcraft/common/carts/EntityLocomotive.java
  src/main/java/mods/railcraft/common/items/ItemOveralls.java
  src/main/java/mods/railcraft/common/modules/ModuleGT5.java
  src/main/java/mods/railcraft/common/modules/ModuleManager.java
  src/main/java/mods/railcraft/common/util/misc/MiscTools.java
Labels: enhancement

#80 add Steam trap protection to players wearing gas and heat hazmat
  dependencies.gradle
  src/main/java/mods/railcraft/common/blocks/machine/alpha/TileSteamTrap.java
Labels: enhancement

#83 add support for IronTank upgrades
  dependencies.gradle
  src/main/java/mods/railcraft/common/carts/EntityCartTank.java
Labels: enhancement

#92 Fix null pointer itemStack crash
  src/main/java/mods/railcraft/common/blocks/tracks/BlockTrack.java
Labels: bug

#93 Rework block breaking to fix anchors not storing their time
  src/main/java/mods/railcraft/common/blocks/machine/BlockMachine.java
Labels: :construction: Testing on Zeta
